version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customersdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password

